apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: splunk-k8s-logging-metadata
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: splunk-k8s-logging-metadata-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: splunk-k8s-logging-metadata
subjects:
  - kind: ServiceAccount
    name: logging-demo-splunk-kubernetes-logging
    namespace: logging-demo